server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/secure_admin
spring.datasource.username=secure_admin
spring.datasource.password=secure_admin

logging.level.com.example.backendapi=DEBUG
logging.level.org.springframework.security=INFO

app.jwt.secret=dev-secret-key-for-learning-only-change-before-production

app.bootstrap.admin.enabled=true
app.bootstrap.admin.username=admin
app.bootstrap.admin.email=admin@example.com
app.bootstrap.admin.password=admin12345
