### List users
GET http://localhost:8080/api/v1/users

### Create user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "john",
  "email": "john@example.com"
}

### Find user by id
GET http://localhost:8080/api/v1/users/1

### Delete user by id
DELETE http://localhost:8080/api/v1/users/1

### Confirm deleted user returns 404
GET http://localhost:8080/api/v1/users/1

