### Register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "john",
  "email": "john@example.com",
  "password": "password123"
}

### Register should fail because email is duplicated
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "johnny",
  "email": "john@example.com",
  "password": "password123"
}

